name: flutter_storyline
description: Display stories just like Instagram & TikTok. Handles preloading, caching and all the hard bits, so you can focus on the UI
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_storyline_android
      ios:
        default_package: flutter_storyline_ios
      linux:
        default_package: flutter_storyline_linux
      macos:
        default_package: flutter_storyline_macos
      web:
        default_package: flutter_storyline_web
      windows:
        default_package: flutter_storyline_windows

dependencies:
  flutter:
    sdk: flutter
  flutter_storyline_android:
    path: ../flutter_storyline_android
  flutter_storyline_ios:
    path: ../flutter_storyline_ios
  flutter_storyline_linux:
    path: ../flutter_storyline_linux
  flutter_storyline_macos:
    path: ../flutter_storyline_macos
  flutter_storyline_platform_interface:
    path: ../flutter_storyline_platform_interface
  flutter_storyline_web:
    path: ../flutter_storyline_web
  flutter_storyline_windows:
    path: ../flutter_storyline_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
