version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_storyline_windows"
    schedule:
      interval: "daily"