name: flutter_storyline_android
description: Android implementation of the flutter_storyline plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: flutter_storyline
    platforms:
      android:
        package: com.example.verygoodcore
        pluginClass: FlutterStorylinePlugin
        dartPluginClass: FlutterStorylineAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_storyline_platform_interface:
    path: ../flutter_storyline_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
