name: flutter_storyline_web
description: Web implementation of the flutter_storyline plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: flutter_storyline
    platforms:
      web:
        pluginClass: FlutterStorylineWeb
        fileName: flutter_storyline_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_storyline_platform_interface:
    path: ../flutter_storyline_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
