name: flutter_storyline_ios

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/flutter_storyline_ios.yaml"
      - "flutter_storyline_ios/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/flutter_storyline_ios.yaml"
      - "flutter_storyline_ios/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.24.0
      working_directory: flutter_storyline_ios

